version: '3'
services:
  group2_fams:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9999:9999
    volumes:
      - ./:/group2_fams
      - /group2_fams/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: sh -c "npm install && npm run dev"

volumes:
  node_modules:
